name: majmua
description: Shelf Muslim.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Html
  flutter_html: ^2.2.1

  # Clipboard and Share's
  share_plus: ^6.3.1
  clipboard: ^0.1.3

  # Path
  path_provider: ^2.0.14
  path: ^1.8.2

  # State management
  provider: ^6.0.5

  # Times
  adhan: ^2.0.0-nullsafety.2
  hijri: ^3.0.0
  intl: ^0.18.0

  # Indicator's
  percent_indicator: ^4.2.3
  square_percent_indicater: ^0.1.0
  smooth_page_indicator: ^1.0.1

  # Cupertino
  cupertino_icons: ^1.0.5

  # Databases
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.6

  # System
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/databases/
    - assets/icons/
    - assets/quran/

  fonts:
    - family: 'Nexa'
      fonts:
      - asset: assets/fonts/nexa_reqular.ttf
    - family: 'Lato'
      fonts:
      - asset: assets/fonts/lato.ttf
    - family: 'Quran'
      fonts:
      - asset: assets/fonts/quran_font.ttf
    - family: 'Scheherazade'
      fonts:
      - asset: assets/fonts/scheherazade.ttf