name: majmua
description: Shelf Muslim.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Html
  flutter_html: ^3.0.0-beta.2

  # Clipboard and Share's
  share_plus: ^7.0.2
  clipboard: ^0.1.3

  # Path
  path_provider: ^2.0.15
  path: ^1.8.2

  # State management
  provider: ^6.0.5

  # Times
  adhan: ^2.0.0-nullsafety.2
  hijri: ^3.0.0
  intl: ^0.18.1

  # Indicator's
  percent_indicator: ^4.2.3
  square_percent_indicater: ^0.1.0
  smooth_page_indicator: ^1.1.0

  # Cupertino
  cupertino_icons: ^1.0.5

  # Databases
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0

  # System
  flu_wake_lock: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/databases/
    - assets/icons/
    - assets/quran/

  fonts:
    - family: 'Nexa'
      fonts:
      - asset: assets/fonts/nexa_reqular.ttf
    - family: 'Lato'
      fonts:
      - asset: assets/fonts/lato.ttf
    - family: 'Quran'
      fonts:
      - asset: assets/fonts/quran_font.ttf
    - family: 'Scheherazade'
      fonts:
      - asset: assets/fonts/scheherazade.ttf
    - family: 'Digital'
      fonts:
      - asset: assets/fonts/digital.ttf
