name: majmua
description: Shelf of the Muslim.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  percent_indicator: ^4.2.4
  square_progress_indicator: ^0.0.7
  smooth_page_indicator: ^1.2.0+3
  sleek_circular_slider: ^2.0.1
  step_progress_indicator: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  scrollable_positioned_list: ^0.3.8
  responsive_builder: ^0.7.1

  # Databases
  sqflite: ^2.4.1
  hive_flutter: ^1.1.0

  # Path
  path: ^1.9.0

  # Copy/Share
  share_plus: ^10.1.4
  clipboard: ^0.1.3

  # State
  provider: ^6.1.2

  # Times
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  intl: ^0.19.0
  timezone: ^0.10.0
  cron: ^0.6.1

  # System
  wakelock_plus: ^1.2.10
  url_launcher: ^6.3.1
  flutter_compass: ^0.8.1
  vibration: ^3.1.2

  # Notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/quran/
    - assets/databases/
    - assets/fonts/
    - assets/pictures/
    - assets/icons/

  fonts:
    - family: 'Gilroy'
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    - family: 'Gilroy medium'
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: 'Hafs'
      fonts:
        - asset: assets/fonts/hafs_regular.ttf
