name: majmua
description: Shelf of the Muslim.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  percent_indicator: ^4.2.3
  square_progress_indicator: ^0.0.7
  smooth_page_indicator: ^1.1.0
  sleek_circular_slider: ^2.0.1
  step_progress_indicator: ^1.0.2
  animated_text_kit: ^4.2.2
  salomon_bottom_bar: ^3.3.2
  scrollable_positioned_list: ^0.3.8

  # Databases
  sqflite: ^2.3.3
  hive_flutter: ^1.1.0

  # Path
  path: ^1.8.3

  # Copy/Share
  share_plus: ^8.0.3
  clipboard: ^0.1.3

  # State
  provider: ^6.1.2

  # Times
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  intl: ^0.18.1
  timezone: ^0.9.2

  # System
  wakelock_plus: ^1.2.4
  url_launcher: ^6.2.6

  # Notifications
  flutter_local_notifications: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/quran/
    - assets/databases/
    - assets/fonts/
    - assets/pictures/
    - assets/icons/

  fonts:
    - family: 'Raleway'
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: 'Gilroy'
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    - family: 'Bitter'
      fonts:
        - asset: assets/fonts/bitter_medium.ttf
    - family: 'Karim'
      fonts:
        - asset: assets/fonts/karim.ttf
