name: majmua
description: JM apps project Majmua

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path: ^1.8.2
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.2
  provider: ^6.0.4
  share_plus: ^6.3.0
  clipboard: ^0.1.3
  percent_indicator: ^4.2.2
  smooth_page_indicator: ^1.0.0+2
  hijri: ^3.0.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/databases/
    - assets/icons/
    - assets/surahs/
    -
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/noto_sans.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Surah
      fonts:
        - asset: assets/fonts/quran_surah.ttf

